### ISSUE TITLE
Vault metadata route

### ISSUE THREAD

**Issue by gpxl-dev** [UmamiDAO/metrics-api#37]
Propose `/vaults`:

```
type Vault = {
  /** this will be a slug used in the URL, so suggest something like `glpusdc` **/
  id: string;
  name: string;
  depositToken: string;
  earnToken: string;
  apr: number;
  fees: {
    deposit: number;
    performance: number;
    management: number;
  };
  capacity: string;
  deposits: string;
};
```

Note that the APR, capacity, and deposits will need to be updated quite frequently. We should consider whether or not it's worth having a separate route for those.

If we do, we _could_ dedupe that data from here, but I don't think it makes sense to send the vault metadata without the performance/capacity data, too.

**Comment by Clonescody** [comment]
Looks good to me, couple of things : 
- I'll add an `address` field with the vault's address
- Are tokens sent as addresses or symbols ? 

As for frequency update, I'll handle that on my side, most of the infos are static once fetched so I'll maintain that in a store and re-fetch the rest

**Comment by Clonescody** [comment]
Also as the vaults will be 4626, having the `pricePerShare` will be nice as well ( for $ value for ex )

**Comment by gpxl-dev** [comment]
Yeah this all makes sense. I think we'll have a separate endpoint for PPS (and other metrics) as well, but it probably doesn't hurt to send it here.

Just realised we also need to know the `receiptToken` address, but this is likely to be the same as the vault's `address` I guess. I will confirm on slack

**Comment by gpxl-dev** [comment]
> Are tokens sent as addresses or symbols ?

Addresses.
